name: Generate Journal Table

on: [push]

jobs:
  build:
    name: Generate Journal Table
    runs-on: r-base
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs R
      - name: Rscript
        run: |
          Rscript R/render_html.R