name: Generate Journal Table

on: [push]

jobs:
  build:
    name: Generate Journal Table
    runs-on: ubuntu-20.04
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step installs R packages
      - name: R packages
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'googlesheets', 'dplyr', 'lubridate', 'DT'))"
      # This step runs R
      - name: Rscript
        run: |
          Rscript R/render_html.R